### ISSUE TITLE
Missing license file/copyright notice

### ISSUE THREAD

**Issue by jramanat** [proj4js/wkt-parser#12]
Hi, we're looking to use proj4js which lists wkt-parser and mgrs as dependencies.  No issues with proj4js + mgrs, but we're getting hung up by the fact that the wkt-parser repo doesn't contain a license file/copyright notice (just the mention of MIT in package.json).  Presumably, it's the same as the other two, but any chance to get this explicitly included in the repo so we can clear legal hurdles?  Thanks!

**Comment by calvinmetcalf** [comment]
fixed

**Comment by jramanat** [comment]
Perfect, thanks for the quick resolution!
