### ISSUE TITLE
Shifted projection for OSNI 1952 Irish National Grid (epsg:29901)

### ISSUE THREAD

**Issue by ksokolowski7** [proj4js/wkt-parser#3]
There is an issue with shifted projection for ONSI 1952 projection.

I am not an expert in geo but I could see that datumCode set to osgb36 works correctly for this projection.

I have created a pull request #2

**Comment by calvinmetcalf** [comment]
from what I can tell [OSNI 1952](https://epsg.io/4188) and [OSGB 1938](https://epsg.io/27700)  aren't identical, so we probably want to add the datum to proj4 [somewhere in here](https://github.com/proj4js/proj4js/blob/master/lib/constants/Datum.js) and then update this one with a similar osni_1952->osni52 rule

**Comment by ksokolowski7** [comment]
I added rule to the datum on proj4js repository. [Pull request #249](https://github.com/proj4js/proj4js/pull/249/files).

Also I added support for other Irish projection where I used the rule 'ire65'
