### ISSUE TITLE
TOWGS84 in datum is ignored

### ISSUE THREAD

**Issue by mbarto** [proj4js/wkt-parser#5]
It should be parsed to datum_params

**Comment by calvinmetcalf** [comment]
do you have an example proj file that does this ?

**Comment by mbarto** [comment]
PROJCS["ED50 / UTM zone 32N", GEOGCS["ED50", DATUM["European Datum 1950", SPHEROID["International 1924", 6378388.0, 297.0, AUTHORITY["EPSG","7022"]], TOWGS84[-116.641, -56.931, -110.559, 0.893, 0.921, -0.917, -3.52], AUTHORITY["EPSG","6230"]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH], AUTHORITY["EPSG","4230"]], PROJECTION["Transverse_Mercator", AUTHORITY["EPSG","9807"]], PARAMETER["central_meridian", 9.0], PARAMETER["latitude_of_origin", 0.0], PARAMETER["scale_factor", 0.9996], PARAMETER["false_easting", 500000.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["Easting", EAST], AXIS["Northing", NORTH], AUTHORITY["EPSG","23032"]]

**Comment by calvinmetcalf** [comment]
great thanks

**Comment by mbarto** [comment]
I also sent a PR to fix it. Feel free to use it or not
